---
title: "Untitled"
output: html_document
date: "2026-08-17"
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(patchwork)
library(ggsci)
library(scales)

geoloop = read_excel("geoloop.xlsx") %>% 
  mutate(TIMESTAMP = as_datetime(TIMESTAMP), GeoloopToBldgT = (GeoloopToBldgT - 32) * 5/9, GeoloopFromBldgT = (GeoloopFromBldgT - 32) * 5/9) %>% 
  filter(GeoloopToBldgT <= 20)
zentra = read_csv("zentra.csv") %>% 
  rename(TIMESTAMP = `z6-22205`, water_level_m = `Port1...2`, water_temp = `Port1...3`, spc = `Port1...4`) %>% 
  mutate(water_level_m = as.numeric(water_level_m) / 1000, water_temp = as.numeric(water_temp), TIMESTAMP = mdy_hms(TIMESTAMP), spc = as.numeric(spc) * 1000) %>% 
  slice(3:n()) %>% 
  select(1:4) %>% 
  filter(TIMESTAMP >= "2026-06-30 00:01:00", TIMESTAMP <= "2026-07-27 23:59:00")
parish = read_csv("parish_dts_xdepth.csv") %>% 
  mutate(dt_cst = datetime - hours(3))
parish_pre <- read_csv("pre_op.csv")%>% 
  mutate(dt_cst = datetime - hours(3))


shade_periods <- geoloop %>%
  arrange(TIMESTAMP) %>%
  mutate(
    shaded = VFDFreq == 30,
    grp = cumsum(shaded != lag(shaded, default = first(shaded)))
  ) %>%
  filter(shaded) %>%
  group_by(grp) %>%
  summarize(
    start = min(TIMESTAMP),
    end = max(TIMESTAMP),
    .groups = "drop"
  )
```


```{r}
llim = as.POSIXct("2026-07-23 0:00:00")
ulim= as.POSIXct("2026-07-25 0:00:00")

llim1 = as.POSIXct("2026-07-06 0:00:00")
ulim1 = as.POSIXct("2026-07-09 0:00:00")
llim2 = as.POSIXct("2026-07-23 0:00:00")
ulim2 = as.POSIXct("2026-07-26 0:00:00")

P1 =
  ggplot(geoloop) + 
  geom_line(aes(x = TIMESTAMP, y = GeoloopToBldgT), linewidth = 1) +
  # annotate(geom = "rect",
  #   xmin = llim1,
  #   xmax = ulim1,
  #   ymin = -Inf,
  #   ymax = Inf,
  #   fill = "red",
  #   alpha = 0.2
  # ) +
  # annotate(
  #   geom = "rect",
  #   xmin = llim2,
  #   xmax = ulim2,
  #   ymin = -Inf,
  #   ymax = Inf,
  #   fill = "red",
  #   alpha = 0.2
  # ) +
  geom_rect(data = shade_periods, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf), fill = "lightblue1", alpha = 0.4) +
  theme_bw(base_size = 18) +
  scale_x_datetime(limits = c(llim, ulim), date_breaks = "6 hours", date_labels = "%b %d\n%H:%M") +
  labs(title = "Production Well Return Water Temperature", x = "Date", y = "Water Temp (Deg. C)")

P2 = 
  ggplot(zentra) + 
  geom_line(aes(x = TIMESTAMP, y = water_level_m), linewidth = 1) +
  # annotate(
  #   geom = "rect",
  #   xmin = llim1,
  #   xmax = ulim1,
  #   ymin = -Inf,
  #   ymax = Inf,
  #   fill = "red",
  #   alpha = 0.2
  # ) +
  # annotate(
  #   geom = "rect",
  #   xmin = llim2,
  #   xmax = ulim2,
  #   ymin = -Inf,
  #   ymax = Inf,
  #   fill = "red",
  #   alpha = 0.2
  # ) +
  geom_rect(data = shade_periods, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf), fill = "lightblue1", alpha = 0.4) +
  scale_x_datetime(limits = c(llim, ulim), date_breaks = "6 hours", date_labels = "%b %d\n%H:%M") +
  theme_bw(base_size = 18) +
  labs(title = "Observation Well Water Height", x = "Date", y = "Water Height (M)")

P3 =
  ggplot(zentra) + 
  geom_line(aes(x = TIMESTAMP, y  = water_temp), linewidth = 1) +
  # annotate(
  #   geom = "rect",
  #   xmin = llim1,
  #   xmax = ulim1,
  #   ymin = -Inf,
  #   ymax = Inf,
  #   fill = "red",
  #   alpha = 0.2
  # ) +
  # annotate(
  #   geom = "rect",
  #   xmin = llim2,
  #   xmax = ulim2,
  #   ymin = -Inf,
  #   ymax = Inf,
  #   fill = "red",
  #   alpha = 0.2
  # ) +
  geom_rect(data = shade_periods, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf), fill = "lightblue1", alpha = 0.4) +
  scale_x_datetime(limits = c(llim, ulim), date_breaks = "6 hours", date_labels = "%b %d\n%H:%M") +
  theme_bw(base_size = 18) +
  labs(title = "Observation Well Water Temperature", x = "Date", y = "Water Temp (Deg. C)")
P1 / P2 / P3 + plot_layout(axes = "collect")

```


```{r}
parish_jul6 = ggplot() +
  geom_rect(data = shade_periods, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf), fill = "lightblue1", alpha = 0.4) +
  geom_line(data = parish %>% filter(depth_m == 22.622), aes(x = dt_cst, y = TMP, color = '75 ft.'), linewidth = 1) +
  geom_line(data = parish %>% filter(depth_m == 38.128), aes(x = dt_cst, y = TMP, color = '125 ft.'), linewidth = 1) +
  geom_line(data = parish %>% filter(depth_m == 53.380), aes(x = dt_cst, y = TMP, color = '175 ft.'), linewidth = 1) +
  geom_line(data = parish %>% filter(depth_m == 68.632), aes(x = dt_cst, y = TMP, color = '225 ft.'), linewidth = 1) +
  scale_x_datetime(limits = c(llim, ulim), date_breaks = "6 hours", date_labels = "%b %d\n%H:%M") +
  theme_bw(base_size = 18) + 
  scale_color_manual(breaks = c("75 ft.", "125 ft.", "175 ft.", "225 ft."), values = c("coral4", "firebrick", "darkorange3", "darkgoldenrod2")) +
  labs(x = "Date", y = "Water Temp (deg. C)", title = "Obs. Well Temperature (DTS Cable)", color = "Depth in Well")

parish_jul23 = ggplot() + 
  geom_rect(data = shade_periods, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf), fill = "lightblue1", alpha = 0.4) + 
  geom_line(data = parish %>% filter(depth_m == 22.622), aes(x = dt_cst, y = TMP, color = '75 ft.'), linewidth = 1) +
  geom_line(data = parish %>% filter(depth_m == 38.128), aes(x = dt_cst, y = TMP, color = '125 ft.'), linewidth = 1) +
  geom_line(data = parish %>% filter(depth_m == 53.380), aes(x = dt_cst, y = TMP, color = '175 ft.'), linewidth = 1) +
  geom_line(data = parish %>% filter(depth_m == 68.632), aes(x = dt_cst, y = TMP, color = '225 ft.'), linewidth = 1) +
  scale_x_datetime(limits = c(llim, ulim), date_breaks = "6 hours", date_labels = "%b %d\n%H:%M") +
  theme_bw(base_size = 18) + 
  scale_color_manual(breaks = c("75 ft.", "125 ft.", "175 ft.", "225 ft."), values = c("darkgoldenrod2", "darkorange1", "firebrick2", "coral4")) +
  labs(x = "Date", y = "Water Temp (deg. C)", title = "Obs. Well Temperature (DTS Cable)", color = "Depth in Well")


P1 / P2 / parish_jul23 + plot_layout(axes = "collect")
```


```{r}

llim = as.POSIXct("2026-07-6 0:00:00")
ulim= as.POSIXct("2026-07-9 0:00:00")

P7 = 
  ggplot(zentra) + 
  geom_line(aes(x = TIMESTAMP, y  = spc), linewidth = 1) +
  geom_rect(data = shade_periods, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf), fill = "lightblue1", alpha = 0.4) +
  scale_x_datetime(limits = c(llim, ulim), date_breaks = "6 hours", date_labels = "%b %d\n%H:%M") +
  theme_bw(base_size = 18) +
  labs(title = "Observation Well Specific Conductivity", x = "Date", y = "SPC (Us/cm)")



P1 =
  ggplot(geoloop) + 
  geom_line(aes(x = TIMESTAMP, y = GeoloopToBldgT), linewidth = 1) +
  # annotate(geom = "rect",
  #   xmin = llim1,
  #   xmax = ulim1,
  #   ymin = -Inf,
  #   ymax = Inf,
  #   fill = "red",
  #   alpha = 0.2
  # ) +
  # annotate(
  #   geom = "rect",
  #   xmin = llim2,
  #   xmax = ulim2,
  #   ymin = -Inf,
  #   ymax = Inf,
  #   fill = "red",
  #   alpha = 0.2
  # ) +
  geom_rect(data = shade_periods, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf), fill = "lightblue1", alpha = 0.4) +
  theme_bw(base_size = 18) +
  scale_x_datetime(limits = c(llim, ulim), date_breaks = "6 hours", date_labels = "%b %d\n%H:%M") +
  labs(title = "Production Well Return Water Temperature", x = "Date", y = "Water Temp (Deg. C)")

P2 = 
  ggplot(zentra) + 
  geom_line(aes(x = TIMESTAMP, y = water_level_m), linewidth = 1) +
  # annotate(
  #   geom = "rect",
  #   xmin = llim1,
  #   xmax = ulim1,
  #   ymin = -Inf,
  #   ymax = Inf,
  #   fill = "red",
  #   alpha = 0.2
  # ) +
  # annotate(
  #   geom = "rect",
  #   xmin = llim2,
  #   xmax = ulim2,
  #   ymin = -Inf,
  #   ymax = Inf,
  #   fill = "red",
  #   alpha = 0.2
  # ) +
  geom_rect(data = shade_periods, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf), fill = "lightblue1", alpha = 0.4) +
  scale_x_datetime(limits = c(llim, ulim), date_breaks = "6 hours", date_labels = "%b %d\n%H:%M") +
  theme_bw(base_size = 18) +
  labs(title = "Observation Well Water Height", x = "Date", y = "Water Height (M)")

P3 =
  ggplot(zentra) + 
  geom_line(aes(x = TIMESTAMP, y  = water_temp), linewidth = 1) +
  # annotate(
  #   geom = "rect",
  #   xmin = llim1,
  #   xmax = ulim1,
  #   ymin = -Inf,
  #   ymax = Inf,
  #   fill = "red",
  #   alpha = 0.2
  # ) +
  # annotate(
  #   geom = "rect",
  #   xmin = llim2,
  #   xmax = ulim2,
  #   ymin = -Inf,
  #   ymax = Inf,
  #   fill = "red",
  #   alpha = 0.2
  # ) +
  geom_rect(data = shade_periods, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf), fill = "lightblue1", alpha = 0.4) +
  scale_x_datetime(limits = c(llim, ulim), date_breaks = "6 hours", date_labels = "%b %d\n%H:%M") +
  theme_bw(base_size = 18) +
  labs(title = "Observation Well Water Temperature", x = "Date", y = "Water Temp (Deg. C)")
P1 / P2 / P7 + plot_layout(axes = "collect")
```

